# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               'A DevOps practitioner's blog'
tagline:             'Powered by Jekyll'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://vinodhsiva.github.io
baseurl:             'http://vinodhsiva.github.io'
paginate:            5

# About/contact
author:
  name:              Siva Muthu
  url:              
  email:             sivamuthu.uk@gmail.com

# Custom vars
version:             1.0.0

theme: jekyll-theme-modernist
